# Common directories
alias code "cd ~/Code"
alias desk "cd ~/Desktop"
alias docs "cd ~/Documents"
alias down "cd ~/Downloads"
alias dot "cd ~/.dotfiles"

# List Files
alias l "tree --dirsfirst --noreport -a -L 1"
alias tree "tree --dirsfirst -I node_modules"

# man
alias man "viman"

# git
alias g "git"
alias gaa "git add --all"
alias gap "git add --patch"
alias gb "git branch"
alias gba "git branch -a"
alias gbnuke "git branch | grep -v master | xargs git branch -D"
alias gc "git commit -v"
alias gcm "git commit -m"
alias gco "git checkout"
alias gcob "git checkout -b"
alias gcod "git checkout develop"
alias gcom "git checkout master"
alias gd "git diff"
alias gds "git diff --stat"
alias gfa "git fetch --all --prune"
alias gl "git pull"
alias glu "git pull --rebase"
alias glg "git log --stat --color"
alias glog "git log --oneline --decorate --color --graph"
alias gm "git merge"
alias gp "git push"
alias gpu "git push --set-upstream"
alias gpt "git push --follow-tags"
alias grbi "git rebase --interactive"
alias grhh "git reset HEAD --hard"
alias groh "git reset origin/master --hard"
alias grv "git remote -v"
alias gsearch "git log -S"
alias gst "git status"
alias gsts "git status -s"
alias gt "git tag"
alias gta "git tag -a"

# npm
alias n "npm"
alias ni "npm i"
alias nig "npm i --global"
alias nis "npm i --save"
alias nisd "npm i --save-dev"
alias nls "npm ls"
alias nr "npm run"
alias nrd "npm run dev"
alias nrt "npm run test"
alias nrtw "npm run test:watch"
