export ZSH=$HOME/.dotfiles/zsh
export DOTFILES=$HOME/.dotfiles
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:/usr/local/sbin"
export EDITOR='nvim'
export CLICOLOR=true
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export PROMPT=$'\n%F{magenta}%~%f $ '
typeset -aU path fpath
